name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"

      - name: Build distribution
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
